name: caPutLog CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup build tools
      run: |
        sudo apt-get update
        sudo apt-get -y install curl make patch m4 build-essential tclx python3-dev git
    - name: Setup & build EPICS base
      run: |
        mkdir epics && cd epics
        curl https://epics-controls.org/download/base/base-7.0.7.tar.gz | tar xz
        cd base-7.0.7
        make
    - name: Build caPutLog
      run: |
        echo "EPICS_BASE=$GITHUB_WORKSPACE/epics/base-7.0.7" >> configure/RELEASE.local
        make
    - name: Run tests
      run:  |
        cd test/O.linux-x86_64/
        ./caPutJsonLogTest
